//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/_Content/InputSystem/InputSystemMovement.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputSystemMovement: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputSystemMovement()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputSystemMovement"",
    ""maps"": [
        {
            ""name"": ""AllTime"",
            ""id"": ""2410fd40-d1ef-442a-a02a-90e8d0726988"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""e3af951a-5b4e-45e4-b2ae-bf375405748b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dab7213b-c391-424d-a153-d68eb9203ac7"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // AllTime
        m_AllTime = asset.FindActionMap("AllTime", throwIfNotFound: true);
        m_AllTime_Pause = m_AllTime.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // AllTime
    private readonly InputActionMap m_AllTime;
    private List<IAllTimeActions> m_AllTimeActionsCallbackInterfaces = new List<IAllTimeActions>();
    private readonly InputAction m_AllTime_Pause;
    public struct AllTimeActions
    {
        private @InputSystemMovement m_Wrapper;
        public AllTimeActions(@InputSystemMovement wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_AllTime_Pause;
        public InputActionMap Get() { return m_Wrapper.m_AllTime; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AllTimeActions set) { return set.Get(); }
        public void AddCallbacks(IAllTimeActions instance)
        {
            if (instance == null || m_Wrapper.m_AllTimeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_AllTimeActionsCallbackInterfaces.Add(instance);
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(IAllTimeActions instance)
        {
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(IAllTimeActions instance)
        {
            if (m_Wrapper.m_AllTimeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IAllTimeActions instance)
        {
            foreach (var item in m_Wrapper.m_AllTimeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_AllTimeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public AllTimeActions @AllTime => new AllTimeActions(this);
    public interface IAllTimeActions
    {
        void OnPause(InputAction.CallbackContext context);
    }
}
