//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Test_scene/InputSystemTest/InputSystemMovement.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputSystemMovement: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputSystemMovement()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputSystemMovement"",
    ""maps"": [
        {
            ""name"": ""AllTime"",
            ""id"": ""2410fd40-d1ef-442a-a02a-90e8d0726988"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""e3af951a-5b4e-45e4-b2ae-bf375405748b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dab7213b-c391-424d-a153-d68eb9203ac7"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ControlScheme"",
            ""id"": ""aeedc490-2d77-4603-bec0-393438b5e74f"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Button"",
                    ""id"": ""d0071202-755e-4982-ac72-0f390d849832"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MelleAttack"",
                    ""type"": ""Button"",
                    ""id"": ""0c2f8ac1-efe5-4033-a8b2-491188c85c8e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DistanceAttack"",
                    ""type"": ""Button"",
                    ""id"": ""5b87042a-2765-4ba4-aad8-8b10e8614921"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem"",
                    ""type"": ""Button"",
                    ""id"": ""1e1df2ea-e1f2-41db-ad6f-279630d7f153"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""7c1c9f39-5b8f-4259-9562-8527cdb5bdd1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""a15efa4e-1a14-4e96-a821-321df36f7525"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7bf82692-615d-4ba5-8da7-2b0210069229"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MelleAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24c8bffa-50b1-46c0-b8db-58c199277673"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DistanceAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5137e63c-9e8b-40ec-a3e3-8f349b7ee2cf"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24d4ac0c-f53d-46c5-b83f-0331dfc9afb5"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a0f698e-9698-4986-8979-0b2ce22f34a6"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d50e56f-0dc0-460f-b24c-23f378631f64"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""New action map"",
            ""id"": ""0486e878-4830-439f-ba8b-26bfd98df683"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""3ab1f6ed-a2a6-4c18-9a8e-2f3b94f334e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3cdd9ffc-8184-4cba-be8b-a17fc122c94f"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // AllTime
        m_AllTime = asset.FindActionMap("AllTime", throwIfNotFound: true);
        m_AllTime_Pause = m_AllTime.FindAction("Pause", throwIfNotFound: true);
        // ControlScheme
        m_ControlScheme = asset.FindActionMap("ControlScheme", throwIfNotFound: true);
        m_ControlScheme_Movement = m_ControlScheme.FindAction("Movement", throwIfNotFound: true);
        m_ControlScheme_MelleAttack = m_ControlScheme.FindAction("MelleAttack", throwIfNotFound: true);
        m_ControlScheme_DistanceAttack = m_ControlScheme.FindAction("DistanceAttack", throwIfNotFound: true);
        m_ControlScheme_UseItem = m_ControlScheme.FindAction("UseItem", throwIfNotFound: true);
        m_ControlScheme_Interaction = m_ControlScheme.FindAction("Interaction", throwIfNotFound: true);
        m_ControlScheme_Dash = m_ControlScheme.FindAction("Dash", throwIfNotFound: true);
        // New action map
        m_Newactionmap = asset.FindActionMap("New action map", throwIfNotFound: true);
        m_Newactionmap_Newaction = m_Newactionmap.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // AllTime
    private readonly InputActionMap m_AllTime;
    private List<IAllTimeActions> m_AllTimeActionsCallbackInterfaces = new List<IAllTimeActions>();
    private readonly InputAction m_AllTime_Pause;
    public struct AllTimeActions
    {
        private @InputSystemMovement m_Wrapper;
        public AllTimeActions(@InputSystemMovement wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_AllTime_Pause;
        public InputActionMap Get() { return m_Wrapper.m_AllTime; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AllTimeActions set) { return set.Get(); }
        public void AddCallbacks(IAllTimeActions instance)
        {
            if (instance == null || m_Wrapper.m_AllTimeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_AllTimeActionsCallbackInterfaces.Add(instance);
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(IAllTimeActions instance)
        {
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(IAllTimeActions instance)
        {
            if (m_Wrapper.m_AllTimeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IAllTimeActions instance)
        {
            foreach (var item in m_Wrapper.m_AllTimeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_AllTimeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public AllTimeActions @AllTime => new AllTimeActions(this);

    // ControlScheme
    private readonly InputActionMap m_ControlScheme;
    private List<IControlSchemeActions> m_ControlSchemeActionsCallbackInterfaces = new List<IControlSchemeActions>();
    private readonly InputAction m_ControlScheme_Movement;
    private readonly InputAction m_ControlScheme_MelleAttack;
    private readonly InputAction m_ControlScheme_DistanceAttack;
    private readonly InputAction m_ControlScheme_UseItem;
    private readonly InputAction m_ControlScheme_Interaction;
    private readonly InputAction m_ControlScheme_Dash;
    public struct ControlSchemeActions
    {
        private @InputSystemMovement m_Wrapper;
        public ControlSchemeActions(@InputSystemMovement wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_ControlScheme_Movement;
        public InputAction @MelleAttack => m_Wrapper.m_ControlScheme_MelleAttack;
        public InputAction @DistanceAttack => m_Wrapper.m_ControlScheme_DistanceAttack;
        public InputAction @UseItem => m_Wrapper.m_ControlScheme_UseItem;
        public InputAction @Interaction => m_Wrapper.m_ControlScheme_Interaction;
        public InputAction @Dash => m_Wrapper.m_ControlScheme_Dash;
        public InputActionMap Get() { return m_Wrapper.m_ControlScheme; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControlSchemeActions set) { return set.Get(); }
        public void AddCallbacks(IControlSchemeActions instance)
        {
            if (instance == null || m_Wrapper.m_ControlSchemeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControlSchemeActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @MelleAttack.started += instance.OnMelleAttack;
            @MelleAttack.performed += instance.OnMelleAttack;
            @MelleAttack.canceled += instance.OnMelleAttack;
            @DistanceAttack.started += instance.OnDistanceAttack;
            @DistanceAttack.performed += instance.OnDistanceAttack;
            @DistanceAttack.canceled += instance.OnDistanceAttack;
            @UseItem.started += instance.OnUseItem;
            @UseItem.performed += instance.OnUseItem;
            @UseItem.canceled += instance.OnUseItem;
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
        }

        private void UnregisterCallbacks(IControlSchemeActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @MelleAttack.started -= instance.OnMelleAttack;
            @MelleAttack.performed -= instance.OnMelleAttack;
            @MelleAttack.canceled -= instance.OnMelleAttack;
            @DistanceAttack.started -= instance.OnDistanceAttack;
            @DistanceAttack.performed -= instance.OnDistanceAttack;
            @DistanceAttack.canceled -= instance.OnDistanceAttack;
            @UseItem.started -= instance.OnUseItem;
            @UseItem.performed -= instance.OnUseItem;
            @UseItem.canceled -= instance.OnUseItem;
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
        }

        public void RemoveCallbacks(IControlSchemeActions instance)
        {
            if (m_Wrapper.m_ControlSchemeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IControlSchemeActions instance)
        {
            foreach (var item in m_Wrapper.m_ControlSchemeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControlSchemeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ControlSchemeActions @ControlScheme => new ControlSchemeActions(this);

    // New action map
    private readonly InputActionMap m_Newactionmap;
    private List<INewactionmapActions> m_NewactionmapActionsCallbackInterfaces = new List<INewactionmapActions>();
    private readonly InputAction m_Newactionmap_Newaction;
    public struct NewactionmapActions
    {
        private @InputSystemMovement m_Wrapper;
        public NewactionmapActions(@InputSystemMovement wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Newactionmap_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_Newactionmap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(NewactionmapActions set) { return set.Get(); }
        public void AddCallbacks(INewactionmapActions instance)
        {
            if (instance == null || m_Wrapper.m_NewactionmapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_NewactionmapActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(INewactionmapActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(INewactionmapActions instance)
        {
            if (m_Wrapper.m_NewactionmapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(INewactionmapActions instance)
        {
            foreach (var item in m_Wrapper.m_NewactionmapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_NewactionmapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public NewactionmapActions @Newactionmap => new NewactionmapActions(this);
    public interface IAllTimeActions
    {
        void OnPause(InputAction.CallbackContext context);
    }
    public interface IControlSchemeActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnMelleAttack(InputAction.CallbackContext context);
        void OnDistanceAttack(InputAction.CallbackContext context);
        void OnUseItem(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
    }
    public interface INewactionmapActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
